
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace EngineTerminal.Views {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainView : Terminal.Gui.Window 
    {
        
    }
}
