name: Publish NuGet Package

on:
  push:
    branches:
      - 0.91-alpha
<<<<<<< HEAD
    paths:
      - 'src/App/GUI/CustomControls/PropertyGrid/**'
=======
>>>>>>> aeb4abb (Add Nuget Publish)

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

<<<<<<< HEAD
    - name: Set dynamic version
      id: set_version
      run: |
        VERSION="0.1.2-exp-${{ github.run_number }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "Using package version: $VERSION"

    - name: Restore dependencies
      run: dotnet restore ./src/App/GUI/CustomControls/PropertyGrid/Terminal.Gui.CustomViews.csproj

    - name: Build
      run: dotnet build ./src/App/GUI/CustomControls/PropertyGrid/Terminal.Gui.CustomViews.csproj --configuration Release --no-restore /p:Version=$VERSION

    - name: Pack
      run: dotnet pack ./src/App/GUI/CustomControls/PropertyGrid/Terminal.Gui.CustomViews.csproj --configuration Release --no-build --output ./nupkgs /p:PackageVersion=$VERSION
=======
    - name: Restore dependencies
      run: dotnet restore ./src/App/GUI/CustomControls/PropertyGrid/Terminal.Gui.CustomViews.csproj

    - name: Build
      run: dotnet build ./src/App/GUI/CustomControls/PropertyGrid/Terminal.Gui.CustomViews.csproj --configuration Release --no-restore

    - name: Pack
<<<<<<< HEAD
      run: dotnet pack ./src/App/GUI/CustomControls/PropertyGrid/PropertyGrid.csproj --configuration Release --no-build --output ./nupkgs
>>>>>>> aeb4abb (Add Nuget Publish)
=======
      run: dotnet pack ./src/App/GUI/CustomControls/PropertyGrid/Terminal.Gui.CustomViews.csproj --configuration Release --no-build --output ./nupkgs
>>>>>>> 613f34a (Update Project Path)

    - name: Push to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
